# Generated by Django 5.2.4 on 2025-10-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100, unique=True)),
                ('found_in', models.TextField(help_text='Devices where this component is typically found')),
                ('health_effect', models.TextField(help_text='Impact on human health')),
                ('environmental_effect', models.TextField(help_text='Impact on environment')),
                ('icon', models.CharField(default='⚠️', help_text='Emoji or icon representation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Component Information',
                'ordering': ['component'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact', models.CharField(max_length=15)),
                ('accepted_items', models.TextField(help_text='Comma-separated list of accepted e-waste items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('desktop', 'Desktop Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer'), ('other', 'Other')], default='other', max_length=20)),
                ('gold_mg', models.DecimalField(decimal_places=2, help_text='Gold content in milligrams', max_digits=10)),
                ('copper_mg', models.DecimalField(decimal_places=2, help_text='Copper content in milligrams', max_digits=10)),
                ('silver_mg', models.DecimalField(decimal_places=2, help_text='Silver content in milligrams', max_digits=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Estimated recovery value in INR', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Points earned from recycling')),
                ('total_recycled', models.IntegerField(default=0, help_text='Total number of devices recycled')),
                ('co2_saved', models.DecimalField(decimal_places=2, default=0, help_text='CO2 saved in kg', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
    ]
